---
apiVersion: v1
kind: Namespace
metadata:
  name: db

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: mercari/mercari-microservices-example/db:latest
          imagePullPolicy: Never
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 250m
              memory: 250

---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: db
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
    - name: grpc
      protocol: TCP
      port: 5000
      targetPort: 5000
