---
apiVersion: v1
kind: Namespace
metadata:
  name: gateway
  labels:
    istio-injection: enabled

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: mercari/mercari-microservices-example/gateway:latest
          imagePullPolicy: Never
          resources:
            limits:
              cpu: 50m
              memory: 50Mi
            requests:
              cpu: 50m
              memory: 50Mi

---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: gateway
spec:
  type: ClusterIP
  selector:
    app: gateway
  ports:
    - name: http
      protocol: TCP
      port: 4000
      targetPort: 4000
    - name: grpc
      protocol: TCP
      port: 5000
      targetPort: 5000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway
  namespace: gateway
spec:
  rules:
    - http:
        paths:
          - path: '/'
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 4000
