---
apiVersion: v1
kind: Namespace
metadata:
  name: authority
  labels:
    istio-injection: enabled

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: authority
spec:
  replicas: 2
  selector:
    matchLabels:
      app: authority
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: authority
    spec:
      containers:
        - name: authority
          image: mercari/mercari-microservices-example/authority:latest
          imagePullPolicy: Never
          resources:
            limits:
              cpu: 50m
              memory: 50Mi
            requests:
              cpu: 50m
              memory: 50Mi

---
apiVersion: v1
kind: Service
metadata:
  name: authority
  namespace: authority
spec:
  type: ClusterIP
  selector:
    app: authority
  ports:
    - name: grpc
      protocol: TCP
      port: 5000
      targetPort: 5000
