---
apiVersion: v1
kind: Namespace
metadata:
  name: item
  labels:
    istio-injection: enabled

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: item
spec:
  replicas: 2
  selector:
    matchLabels:
      app: item
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: item
    spec:
      containers:
        - name: item
          image: mercari/mercari-microservices-example/item:latest
          imagePullPolicy: Never
          resources:
            limits:
              cpu: 50m
              memory: 50Mi
            requests:
              cpu: 50m
              memory: 50Mi

---
apiVersion: v1
kind: Service
metadata:
  name: item
  namespace: item
spec:
  type: ClusterIP
  selector:
    app: item
  ports:
    - name: grpc
      protocol: TCP
      port: 5000
      targetPort: 5000
